name: Setup Node and install dependencies
description: Setup Node from .nvmrc and install npm dependencies with caching (expects repo to be already checked out)

runs:
  using: composite
  steps:
    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Verify npm and node versions
      run: |
        echo "Node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "package-lock.json exists: $(test -f package-lock.json && echo 'YES' || echo 'NO')"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Debug before install
      run: |
        echo "=== Checking files ==="
        ls -la | grep package
        echo ""
        echo "=== package.json exists? ==="
        cat package.json | head -n 20
        echo ""
        echo "=== package-lock.json exists? ==="
        test -f package-lock.json && echo "YES" || echo "NO"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Install dependencies
      run: |
        echo "=== Running npm install ==="
        npm install --legacy-peer-deps --no-audit
        echo ""
        echo "=== Install completed, checking results ==="
        ls -la node_modules/ | head -n 20
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Verify Angular CLI installation
      run: |
        echo "Checking node_modules..."
        ls -la node_modules/.bin/ng 2>/dev/null || echo "❌ ng binary not found!"
        echo ""
        echo "Checking @angular/cli package..."
        test -d node_modules/@angular/cli && echo "✅ @angular/cli directory exists" || echo "❌ @angular/cli not installed!"
        echo ""
        echo "Angular CLI version:"
        npx ng version || npm list @angular/cli
      shell: bash
      working-directory: ${{ github.workspace }}
