name: Setup Node, checkout and install dependencies
description: Checkout repository, setup Node from .nvmrc and install npm dependencies with caching

runs:
  using: composite
  steps:
    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash
